coffee = require "js2coffee"
fs     = require "fs"
path   = require "path"
Tree   = require "./tree"

module.exports = class

  constructor: ({ @paths }) ->
    @buildIndices dir for dir in @paths

  buildIndices: (dir) ->
    new Tree { dir, @onTree }

  onTree: ({ name, tree, fpath }) ->
    rm = new RegExp fpath, "g"

    out = coffee.build "module.exports = #{JSON.stringify tree}"
    out = out.code
    out = out.replace(rm, ".").replace /'/g, ""
    out = out.replace /require/g, "-> require"
    out = """
    # Generated by `gulp index`.
    #
    
    """ + out

    fs.writeFileSync(
      "#{fpath}/index.coffee"
      out
    )
